Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: MC-VIDEO-GA
      
# Resources:
#   S3Bucket:
#     Type: 'AWS::S3::Bucket'
#     Properties:
#       # AccessControl: Private
#       BucketName: MC-VIDEO-GA
      # BucketEncryption:
      #   ServerSideEncryptionConfiguration:
      #     - ServerSideEncryptionByDefault:
      #         SSEAlgorithm: AES256